### ISSUE TITLE
Add link

### ISSUE THREAD

**Issue by paulinfosum** [infosum/infosum-docs#15]
https://github.com/infosum/infosum-docs/blob/6ae6122e2a1958f52f50f47155b3fbc4acf0d492/docs/filevaults/index.md?plain=1#L3

Suggest adding a link to description of Blob storage from "blob storage area" text.

**Comment by ukmadlz** [comment]
We don't have a description of what blob storage is, unless I link to an external reference?

**Comment by paulinfosum** [comment]
External is fine.
