### ISSUE TITLE
Missing Info

### ISSUE THREAD

**Issue by paulinfosum** [infosum/infosum-docs#31]
https://github.com/infosum/infosum-docs/blob/18c60af58f8a619b788dc241bf342758e53e1c31/docs/getting-started/index.md?plain=1#L5

I think we need an Overview here, along the lines of:

**Overview**
"The InfoSum API enables you to communicate with a wide range of (Windows/Linux/Apple?) progamming environments. You can use the API to interface with InfoSum Platform services and integrate with your platform architecture."

### How it works
How do I install or access the API? Is there a dedicated InfoSum API or do I need to download the API from a website (e.g. Postman) or does InfosSum have their own public API I can use? 
Do I need to create an API account? If so, how do I register for it.  Are there any configurations/changes I need to make? 
Do I have the same access rights/permissions as for my InfoSum account?

### Logging in
How do I log in to the API.

**Comment by ukmadlz** [comment]
The initial sentence isn't correct, in terms of developer documentation, as an API is environment and language agnostic as it's a common interface.

However the 2nd sentence, does make sense. Would it be ok to include alone?
> You can use the API to interface with InfoSum Platform services and integrate with your platform architecture.

As for the bullet points these are not API related information, other than the final point that's dealt with via the `Authentication` guide

**Comment by paulinfosum** [comment]
Thank you for clarifying - please ignore my suggestion and include the second sentence on it's own.

Re bullets, thanks for clarifying. Would it be worth adding something about the API itself, e.g.  "InfoSum's API is a <state type of API e.g  JSON-based OAuth> API. All requests are made to endpoints beginning:
 https://api.infosum.com"

**Comment by paulinfosum** [comment]
Please add your suggested sentence under the bullets:

"You can use the API to interface with InfoSum Platform services and integrate with your platform architecture."
