### ISSUE TITLE
Imports are only tasks once they've been executed

### ISSUE THREAD

**Issue by clwinder** [infosum/infosum-docs#41]
Under the “Uploading a file from AWS S3 to a File Vault” section in the getting started guide, under “Create an Import task” it’s only a task once it’s been executed - “you will need an Import task to execute the import” here you’re creating an Import, not a task

**Comment by paulinfosum** [comment]
change completed, see https://github.com/infosum/infosum-docs/pull/55

**Comment by paulinfosum** [comment]
request completed, see https://github.com/infosum/infosum-docs/pull/55
