### ISSUE TITLE
Data filter on the Import is a separate thing to the filter on the ICC

### ISSUE THREAD

**Issue by clwinder** [infosum/infosum-docs#42]
Under the “Uploading a file from AWS S3 to a File Vault” section in the getting started guide, under “Create an Import task” is "The data_filter contains the filter, which is an array of filters from the ICC". The data filter on the Import is a completely separate thing to the filter on the ICC - it is used to further filter the files allowed by the ICC. For example, the ICC might allow “a.csv, b.csv, c.csv”, then the Import could have a list of specific files “a.csv, b.csv”, only a.csv and b.csv will be imported. The examples of ICC & Import seem to be fine, it's just the wording of this bullet point that could do with clarifying.

**Comment by paulinfosum** [comment]
updated in API docs, here https://github.com/infosum/infosum-docs/pull/57

However, the incorrect text also appears in Sigma API doc in "Create an Import" > "data_filter" so will need to be changed there too.

**Comment by paulinfosum** [comment]
Description is updated in API Reference page
