### ISSUE TITLE
"GCS" is missing from page heading

### ISSUE THREAD

**Issue by paulinfosum** [infosum/infosum-docs#48]
https://github.com/infosum/infosum-docs/blob/0dae87b436ef6d794538f6fe48b4c27383765660/docs/getting-started/uploading-a-file-from-aws-s3-to-a-cloudvault.mdx?plain=1#L9

Please add "Google GCS" to the heading, i.e.:

"Uploading a file from AWS S3 or Google GCS to a Cloud Vault"

**Comment by ukmadlz** [comment]
That will be a separate guide, but I don't have GCS access currently to write and test that

**Comment by jason-tye** [comment]
Guide has been removed as it was outdated. Will ensure that future guides cover uploading from various sources.
